### PR TITLE
Add package metadata

### PR DESCRIPTION
**Pull request by joelverhagen**
Depends on https://github.com/agabani/PassThroughProxy/pull/5.

If #5 is merged first, the diff should look like this:
https://github.com/joelverhagen/PassThroughProxy/compare/library...joelverhagen:package

It is possible to use .csproj metadata specify .nupkg package metadata. I recommend this route for producing a PassThroughProxy package. I have done so here:
https://www.nuget.org/packages/Knapcode.PassThroughProxy/1.2.0-alpha2

I'd love this to become an official package so please feel free to change this package metadata however you want.

### CODE REVIEW

**Comment by agabani** [comment]
Let me know when this is no longer WIP, thank you for all the contributions.

**Comment by joelverhagen** [comment]
Great, I should be able to work on this soon. I'll make an initial attempt at the package metadata. Since the metadata is pretty visible on NuGet.org and (if you are willing) I'd hope to push the official package I basically just want to not have this package as visible as an "official" one:
https://www.nuget.org/packages/Knapcode.PassThroughProxy

Once the official one is published, I'll unlist mine.

Note that if you want me to manage the NuGet.org part, I can push the package and add you as an owner. Your call. I am pretty comfortable with the NuGet.org part since that's my day job 😆.

**Comment by agabani** [comment]
> Note that if you want me to manage the NuGet.org part, I can push the package and add you as an owner. Your call. I am pretty comfortable with the NuGet.org part since that's my day job.

Feel free to push the package.

**Comment by joelverhagen** [comment]
@agabani, I've updated the PR. It looks like you gave me push permissions to this repository. How do you want me to handle this? Should I merge the PR myself? Do you want to sign off on all changes?

I'm happy to take whatever role you are comfortable with.

Removed WIP.

**Comment by agabani** [comment]
Add your self as an author, and merge the pr yourself if it is minor changes like these. 👍

**Comment by joelverhagen** [comment]
Done. Published to NuGet.org:
https://www.nuget.org/packages/PassThroughProxy/1.0.0

Also, I've added you as an owner of the package.

**Pull request merged**
